language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t karolinak1904/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true karolinak1904/docker-react npm run test